# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
- {name: 'Patents and Publications', folder: 'pages', file: 'resources.html'}
- {name: 'Github Projects', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Legacy', folder: 'pages', file: 'documentation.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/marakhmusic'}
- {icon: 'facebook', link: 'https://www.facebook.com/mansoorkhansitar'}
- {icon: 'instagram', link: 'https://www.instagram.com/marakhmusic/'}
- {icon: 'envelope', link: 'mailto:mansoor.aiesec@gmail.com'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCmjJ8HKZvoDGcF6EPf0B6aQ'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Khan'
  previous_page: 'Mansoor'

#sharing_button_prompt: 'Feel free to share!'
#
#related_posts: 'You may also enjoy...'
#
#post_date_prefix: 'Written on'
